return {
    ["Jugner Forest"] = {
        {
            ["name"] = "Forest Prowler",
            ["level_range"] = "10-19",
            ["position"] = "F-8",
            ["notes"] = "Against West wall",
            ["equipment"] = "15 Feet",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
    },
    ["Valkurm Dunes"] = {
        {
            ["name"] = "Sandlord Sultan",
            ["level_range"] = "10-19",
            ["position"] = "E-8",
            ["notes"] = "Corner of cliff",
            ["equipment"] = "15 Hands",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
    },
    ["Buburimu Peninsula"] = {
        {
            ["name"] = "Puffer Pugil",
            ["level_range"] = "10-19",
            ["position"] = "G-9",
            ["notes"] = "Hidden beach",
            ["equipment"] = "15 Hands",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Meriphataud Mountains"] = {
        {
            ["name"] = "Clever Girl",
            ["level_range"] = "10-19",
            ["position"] = "H-11",
            ["notes"] = "",
            ["equipment"] = "15 Feet",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Pashhow Marshlands"] = {
        {
            ["name"] = "Sludge Walker",
            ["level_range"] = "10-19",
            ["position"] = "J-7",
            ["notes"] = "",
            ["equipment"] = "15 Legs",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
    },
    ["West Sarutabaruta [S]"] = {
        {
            ["name"] = "Lepidoptera",
            ["level_range"] = "10-19",
            ["position"] = "J-6",
            ["notes"] = "",
            ["equipment"] = "15 Head",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
        {
            ["name"] = "Poroggo Master",
            ["level_range"] = "30-39",
            ["position"] = "H-9",
            ["notes"] = "",
            ["equipment"] = "25 Feet",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["East Ronfaure [S]"] = {
        {
            ["name"] = "Pelagius (Sheep)",
            ["level_range"] = "10-19",
            ["position"] = "I-8/J-8",
            ["notes"] = "Against the mountain",
            ["equipment"] = "15 Head",
            ["element"] = "Thunder",
            ["crest"] = "Tundra Crest",
        },
        {
            ["name"] = "Madame Rouge",
            ["level_range"] = "40-49",
            ["position"] = "H-9",
            ["notes"] = "?",
            ["equipment"] = "?",
            ["element"] = "",
            ["crest"] = "?",
        },
    },
    ["North Gustaberg [S]"] = {
        {
            ["name"] = "Buzzard",
            ["level_range"] = "10-19",
            ["position"] = "H-8",
            ["notes"] = "",
            ["equipment"] = "15 Head",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
    },
    ["Batallia Downs"] = {
        {
            ["name"] = "Sinister Weapon",
            ["level_range"] = "20-29",
            ["position"] = "K-10",
            ["notes"] = "West",
            ["equipment"] = "15 Legs",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
    },
    ["Korroloka Tunnel"] = {
        {
            ["name"] = "Miter Worm",
            ["level_range"] = "20-29",
            ["position"] = "F-10",
            ["notes"] = "Map 1",
            ["equipment"] = "15 Body",
            ["element"] = "Earth",
            ["crest"] = "Desert Crest",
        },
    },
    ["Rolanberry Fields"] = {
        {
            ["name"] = "Saena",
            ["level_range"] = "20-29",
            ["position"] = "I-9",
            ["notes"] = "N edge, against the mountain",
            ["equipment"] = "15 Legs",
            ["element"] = "",
            ["crest"] = "Ocean Crest",
        },
    },
    ["Sauromugue Champaign"] = {
        {
            ["name"] = "Feral Feline",
            ["level_range"] = "20-29",
            ["position"] = "L-7",
            ["notes"] = "NE Corner",
            ["equipment"] = "15 Legs",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Qufim Island"] = {
        {
            ["name"] = "Trimmer",
            ["level_range"] = "20-29",
            ["position"] = "F-7",
            ["notes"] = "In small alcove",
            ["equipment"] = "15 Body",
            ["element"] = "Thunder",
            ["crest"] = "Tundra Crest",
        },
    },
    ["Yuhtunga Jungle"] = {
        {
            ["name"] = "Cheeky Opo-Opo",
            ["level_range"] = "20-29",
            ["position"] = "G-6",
            ["notes"] = "",
            ["equipment"] = "15 Body",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
    },
    ["Batallia Downs [S]"] = {
        {
            ["name"] = "Joyfly",
            ["level_range"] = "30-39",
            ["position"] = "J-8/J-9/K-8/K-9",
            ["notes"] = "Corners by EXP Book 1st Batallia teleport",
            ["equipment"] = "25 Feet",
            ["element"] = "Thunder",
            ["crest"] = "Tundra Crest",
        },
        {
            ["name"] = "Woodland Lynx",
            ["level_range"] = "40-49",
            ["position"] = "D-5/E-5",
            ["notes"] = "EXP Book 2nd Batallia teleport",
            ["equipment"] = "25 Body",
            ["element"] = "Thunder",
            ["crest"] = "Tundra Crest",
        },
    },
    ["Eastern Altepa Desert"] = {
        {
            ["name"] = "Desert Grazer",
            ["level_range"] = "30-39",
            ["position"] = "I-6",
            ["notes"] = "",
            ["equipment"] = "25 Head",
            ["element"] = "Earth",
            ["crest"] = "Desert Crest",
        },
    },
    ["Sea Serpent Grotto"] = {
        {
            ["name"] = "Regal Leech",
            ["level_range"] = "30-39",
            ["position"] = "K-7",
            ["notes"] = "",
            ["equipment"] = "25 Hands",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
    },
    ["The Sanctuary of Zi'Tah"] = {
        {
            ["name"] = "?",
            ["level_range"] = "30-39",
            ["position"] = "G-9",
            ["notes"] = "NE",
            ["equipment"] = "25 Head",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
    },
    ["Yhoator Jungle"] = {
        {
            ["name"] = "Marble Lizard",
            ["level_range"] = "30-39",
            ["position"] = "G-7",
            ["notes"] = "",
            ["equipment"] = "25 Hands",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
    },
    ["Crawlers' Nest"] = {
        {
            ["name"] = "Monarch Crawler",
            ["level_range"] = "40-49",
            ["position"] = "I-9",
            ["notes"] = "Map 3",
            ["equipment"] = "25 Legs",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
        {
            ["name"] = "Burrow Lord",
            ["level_range"] = "50-59",
            ["position"] = "E-7",
            ["notes"] = "Map 3",
            ["equipment"] = "35 Hands",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
    },
    ["Garlaige Citadel"] = {
        {
            ["name"] = "Fortress Bat",
            ["level_range"] = "40-49",
            ["position"] = "G-9",
            ["notes"] = "Map 1",
            ["equipment"] = "25 Legs",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Gustav Tunnel"] = {
        {
            ["name"] = "Tunnel Lizard",
            ["level_range"] = "40-49",
            ["position"] = "K-8",
            ["notes"] = "Map 1",
            ["equipment"] = "25 Legs",
            ["element"] = "Earth",
            ["crest"] = "Desert Crest",
        },
    },
    ["Labyrinth of Onzozo"] = {
        {
            ["name"] = "Lady of Onzozo",
            ["level_range"] = "40-49",
            ["position"] = "I-8",
            ["notes"] = "From the south",
            ["equipment"] = "25 Legs",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Rolanberry Fields [S]"] = {
        {
            ["name"] = "Solitary Slug",
            ["level_range"] = "40-49",
            ["position"] = "D-9",
            ["notes"] = "",
            ["equipment"] = "25 Body",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
        {
            ["name"] = "?",
            ["level_range"] = "50-59",
            ["position"] = "?",
            ["notes"] = "",
            ["equipment"] = "?",
            ["element"] = "",
            ["crest"] = "?",
        },
    },
    ["Sauromugue Champaign [S]"] = {
        {
            ["name"] = "Terrolynx",
            ["level_range"] = "40-49",
            ["position"] = "I-6",
            ["notes"] = "",
            ["equipment"] = "25 Body",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Western Altepa Desert"] = {
        {
            ["name"] = "Adaman Beetle",
            ["level_range"] = "40-49",
            ["position"] = "H-7",
            ["notes"] = "NW corner",
            ["equipment"] = "25 Body",
            ["element"] = "Earth",
            ["crest"] = "Desert Crest",
        },
    },
    ["Bostaunieux Oubliette"] = {
        {
            ["name"] = "Dreadhund",
            ["level_range"] = "50-59",
            ["position"] = "H-8",
            ["notes"] = "Square room west of Shii",
            ["equipment"] = "35 Feet",
            ["element"] = "Thunder",
            ["crest"] = "Tundra Crest",
        },
    },
    ["Kuftal Tunnel"] = {
        {
            ["name"] = "?",
            ["level_range"] = "50-59",
            ["position"] = "H-10",
            ["notes"] = "",
            ["equipment"] = "35 Head",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Quicksand Caves"] = {
        {
            ["name"] = "?",
            ["level_range"] = "50-59",
            ["position"] = "?",
            ["notes"] = "",
            ["equipment"] = "?",
            ["element"] = "",
            ["crest"] = "?",
        },
    },
    ["Uleguerand Range"] = {
        {
            ["name"] = "Icehoof",
            ["level_range"] = "50-59",
            ["position"] = "G-10",
            ["notes"] = "",
            ["equipment"] = "35 Head",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Aydeewa Subterrane"] = {
        {
            ["name"] = "Nightmite",
            ["level_range"] = "60-69",
            ["position"] = "G-10",
            ["notes"] = "Enter from Wajaom Woodlands #1 near Al Zahbi, drop D, drop E, south to G-10 on stairs",
            ["equipment"] = "35 Legs",
            ["element"] = "Light",
            ["crest"] = "Mountain Crest",
        },
    },
    ["Caedarva Mire"] = {
        {
            ["name"] = "Flesh Lord",
            ["level_range"] = "60-69",
            ["position"] = "J-7",
            ["notes"] = "Azouph Isle Staging Point",
            ["equipment"] = "35 Legs",
            ["element"] = "Thunder",
            ["crest"] = "Tundra Crest",
        },
    },
    ["Bhaflau Thickets"] = {
        {
            ["name"] = "Vile Vine",
            ["level_range"] = "60-69",
            ["position"] = "H-7",
            ["notes"] = "Map 1",
            ["equipment"] = "35 Body",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
    },
    ["Bibiki Bay"] = {
        {
            ["name"] = "Bibiki Stomper",
            ["level_range"] = "60-69",
            ["position"] = "F-9",
            ["notes"] = "",
            ["equipment"] = "35 Body",
            ["element"] = "Water",
            ["crest"] = "Ocean Crest",
        },
    },
    ["Cape Teriggan"] = {
        {
            ["name"] = "Cape Calcatrix",
            ["level_range"] = "60-69",
            ["position"] = "I-8",
            ["notes"] = "West side",
            ["equipment"] = "35 Body",
            ["element"] = "Earth",
            ["crest"] = "Desert Crest",
        },
    },
    ["The Boyahda Tree"] = {
        {
            ["name"] = "Ancient Mold",
            ["level_range"] = "60-69",
            ["position"] = "J-8",
            ["notes"] = "Map 1",
            ["equipment"] = "35 Body",
            ["element"] = "Wind",
            ["crest"] = "Forest Crest",
        },
    },
}